### ISSUE TITLE
Issues in 3.1

### ISSUE THREAD

**Issue by dan-kez** [maxdemarzi/neo_listens#1]
Thanks for creating this example! I'm hoping to structure my trigger off of this template. However in neo4j 3.1 I'm receiving the following error:

```
2016-10-19 13:33:29.564+0000 INFO  Starting...
2016-10-19 13:33:40.064+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@12b57aef' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@12b57aef' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@12b57aef' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:227)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@12b57aef' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:199)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /home/ubuntu/neo4j-community-3.1.0-BETA1/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:186)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:57)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@1572007e' failed to initialize. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:415)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:182)
        ... 9 more
Caused by: java.lang.AbstractMethodError
        at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:69)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:405)
        ... 12 more
```

Any thoughts on this?

**Comment by maxdemarzi** [comment]
Did you update the POM to the version you are using?
https://github.com/maxdemarzi/neo_listens/blob/master/pom.xml#L12

Which version specifically did you try?

**Comment by dan-kez** [comment]
I hadn't. I am using version `3.1.0-BETA1`

I updated it and am now getting the following compilation errors:

```
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.maxdemarzi:triggers:jar:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 31, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building triggers 1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ triggers ---
[INFO] Deleting /home/ubuntu/neo4j-community-3.1.0-BETA1/neo_listens/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ triggers ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ triggers ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 5 source files to /home/ubuntu/neo4j-community-3.1.0-BETA1/neo_listens/target/classes
[INFO] /home/ubuntu/neo4j-community-3.1.0-BETA1/neo_listens/src/main/java/com/maxdemarzi/RegisterTransactionEventHandlerExtensionFactory.java: /home/ubuntu/neo4j-community-3.1.0-BETA1/neo_listens/src/main/java/com/maxdemarzi/RegisterTransactionEventHandlerExtensionFactory.java uses unchecked or unsafe operations.
[INFO] /home/ubuntu/neo4j-community-3.1.0-BETA1/neo_listens/src/main/java/com/maxdemarzi/RegisterTransactionEventHandlerExtensionFactory.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/ubuntu/neo4j-community-3.1.0-BETA1/neo_listens/src/main/java/com/maxdemarzi/RegisterTransactionEventHandlerExtensionFactory.java:[11,8] com.maxdemarzi.RegisterTransactionEventHandlerExtensionFactory is not abstract and does not override abstract method newInstance(org.neo4j.kernel.impl.spi.KernelContext,com.maxdemarzi.RegisterTransactionEventHandlerExtensionFactory.Dependencies) in org.neo4j.kernel.extension.KernelExtensionFactory
[ERROR] /home/ubuntu/neo4j-community-3.1.0-BETA1/neo_listens/src/main/java/com/maxdemarzi/RegisterTransactionEventHandlerExtensionFactory.java:[21,5] method does not override or implement a method from a supertype
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.600 s
[INFO] Finished at: 2016-10-19T15:35:11+00:00
[INFO] Final Memory: 25M/310M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project triggers: Compilation failure: Compilation failure:
[ERROR] /home/ubuntu/neo4j-community-3.1.0-BETA1/neo_listens/src/main/java/com/maxdemarzi/RegisterTransactionEventHandlerExtensionFactory.java:[11,8] com.maxdemarzi.RegisterTransactionEventHandlerExtensionFactory is not abstract and does not override abstract method newInstance(org.neo4j.kernel.impl.spi.KernelContext,com.maxdemarzi.RegisterTransactionEventHandlerExtensionFactory.Dependencies) in org.neo4j.kernel.extension.KernelExtensionFactory
[ERROR] /home/ubuntu/neo4j-community-3.1.0-BETA1/neo_listens/src/main/java/com/maxdemarzi/RegisterTransactionEventHandlerExtensionFactory.java:[21,5] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by maxdemarzi** [comment]
Try the latest version.

**Comment by dan-kez** [comment]
Thank you so much! It's running now.

I'm only seeing the following 3 lines in the console when running through the example:

```
CREATE (max:User {name:"Max"}) RETURN max;

CREATE (al:Suspect {name:"Al Capone"}) RETURN al;

MATCH (max:User),(al:Suspect)
WHERE max.name = "Max" AND al.name = "Al Capone"
CREATE (max)-[r:KNOWS]->(al)
RETURN r;

CREATE (monica:User {name:"Monica"}) RETURN monica;

MATCH (max:User),(monica:User)
WHERE max.name = "Max" AND monica.name = "Monica"
CREATE (max)-[r:KNOWS]->(monica)
RETURN r;

MATCH (monica:User)
WHERE monica.name = "Monica"
SET monica :Suspect
RETURN monica;
```

```
A new Suspect has been created!
A new direct relationship to a Suspect has been created!
A new indirect relationship to a Suspect has been created!
```

Not a big deal as at least the frame work is there to build off of but I figured I'd post the issue here.
