### ISSUE TITLE
Triggers are not working while building a fatJar

### ISSUE THREAD

**Issue by aalampally** [maxdemarzi/neo_listens#4]
I followed this tutorial for testing triggers and everything worked seamlessly. For my usecase, I had to build a fatJar using maven-assembly-plugin with one of the external packages. After building the jar, placing it in plugins folder and starting the neo4j server, the server shuts down with the following error.

Here, I am using neo4j and neo4j-kernel versions as 3.4.0 as my neo4j server is running on 3.4 version. Can someone please help me in solving this issue?
```
2018-08-10 07:22:26.346+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5a6d30e2' was successfully initialized, but failed to start. Please see the attached cause exception "It is not allowed to define functions in the root namespace please use a namespace, e.g. `@UserFunction("org.example.com.randomUUID")". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5a6d30e2' was successfully initialized, but failed to start. Please see the attached cause exception "It is not allowed to define functions in the root namespace please use a namespace, e.g. `@UserFunction("org.example.com.randomUUID")".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5a6d30e2' was successfully initialized, but failed to start. Please see the attached cause exception "It is not allowed to define functions in the root namespace please use a namespace, e.g. `@UserFunction("org.example.com.randomUUID")".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5a6d30e2' was successfully initialized, but failed to start. Please see the attached cause exception "It is not allowed to define functions in the root namespace please use a namespace, e.g. `@UserFunction("org.example.com.randomUUID")".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /Users/anirudhalampally/Downloads/neo4j-community-3.4.0/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@58472096' was successfully initialized, but failed to start. Please see the attached cause exception "It is not allowed to define functions in the root namespace please use a namespace, e.g. `@UserFunction("org.example.com.randomUUID")".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	... 9 more
Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: It is not allowed to define functions in the root namespace please use a namespace, e.g. `@UserFunction("org.example.com.randomUUID")
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler.rejectEmptyNamespace(ReflectiveProcedureCompiler.java:974)
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler.compileFunction(ReflectiveProcedureCompiler.java:328)
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler.compileFunction(ReflectiveProcedureCompiler.java:148)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:91)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:78)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:323)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2018-08-10 07:22:26.348+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by aalampally** [comment]
@maxdemarzi your inputs on this?

**Comment by hoyski** [comment]
We didn't have any luck using maven-assembly-plugin on our project. However, the maven-shade-plugin works fine for us to generate a deployable "one jar" for our trigger.
