### ISSUE TITLE
Incompatible with 3.5 release

### ISSUE THREAD

**Issue by rarebres** [maxdemarzi/neo_listens#5]
This was working while I tested Neo4j enterprise 3.4.9, but yielded errors when I tested it with Neo4j community 3.5.1 with the same triggers-1.0.jar file.  The error at startup is related to a missing class "org/neo4j/kernel/impl/logging/LogService", and was resolved by removal of triggers-1.0.jar from the plugins directory.  An incompatible version of APOC jar can cause the same issue, but I'm using the correct version of that.  So I suspect an update of this trigger code is needed for compatibility with the 3.5 release.

OUTPUT:
ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@26ceffa8' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@26ceffa8' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@26ceffa8' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:184)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:123)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@26ceffa8' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:177)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /media/ebs/neo4j-community-3.5.1/data/databases
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:135)
        at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:40)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:78)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalKernelExtensions@2796aeae' failed to initialize. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:434)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
        ... 9 more
Caused by: org.neo4j.kernel.extension.FailedToBuildKernelExtensionException: Failed to build kernel extension KernelExtension:RegisterTransactionEventHandlerExtensionFactory[registerTransactionEventHandler] because it is compiled with a reference to a class, method, or field, that is not in the class path: 'org/neo4j/kernel/impl/logging/LogService'. The most common cause of this problem, is that Neo4j has been upgraded without also upgrading allinstalled extensions, such as APOC. Make sure that all of your extensions are build against your specific version of Neo4j.
        at org.neo4j.kernel.extension.KernelExtensionFailureStrategies.wrap(KernelExtensionFailureStrategies.java:60)
        at org.neo4j.kernel.extension.KernelExtensionFailureStrategies.access$100(KernelExtensionFailureStrategies.java:26)
        at org.neo4j.kernel.extension.KernelExtensionFailureStrategies$1.handle(KernelExtensionFailureStrategies.java:76)
        at org.neo4j.kernel.extension.AbstractKernelExtensions.init(AbstractKernelExtensions.java:72)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:413)
        ... 12 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/logging/LogService
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetPublicMethods(Class.java:2902)
        at java.lang.Class.getMethods(Class.java:1615)
        at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
        at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
        at java.lang.reflect.WeakCache.get(WeakCache.java:127)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
        at org.neo4j.kernel.impl.util.DependenciesProxy.dependencies(DependenciesProxy.java:55)
        at org.neo4j.kernel.extension.AbstractKernelExtensions.getKernelExtensionDependencies(AbstractKernelExtensions.java:114)
        at org.neo4j.kernel.extension.AbstractKernelExtensions.init(AbstractKernelExtensions.java:61)
        ... 13 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.impl.logging.LogService
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 28 more
2018-12-21 22:43:39.724+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by maxdemarzi** [comment]
Try the latest.
